name: blockly
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  
  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.5+1

  # Network
  dio: ^5.9.1

  # Code generation
  json_annotation: ^4.10.0

  # Utils
  intl: ^0.20.2
  envied: ^1.3.2
  get_it: ^9.2.0

dev_dependencies:
  
  flutter_test:
    sdk: flutter

  # Linter
  very_good_analysis: ^10.0.0

  # Code generation
  build_runner: ^2.11.0
  json_serializable: ^6.12.0
  envied_generator: ^1.3.2

  # Test
  mockito: ^5.6.3


flutter:
  uses-material-design: true
